create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0
);

create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0
);

alter table public.categories enable row level security;
alter table public.payment_methods enable row level security;

create policy "Allow public category access" on public.categories
  for all to anon using (true) with check (true);

create policy "Allow public payment method access" on public.payment_methods
  for all to anon using (true) with check (true);

insert into public.categories (name, sort_order)
values
  ('食費', 0), ('外食', 1), ('日用品', 2), ('バドミントン', 3),
  ('自動車', 4), ('交通費', 5), ('固定費', 6), ('その他', 7)
on conflict (name) do nothing;

insert into public.payment_methods (name, sort_order)
values ('現金', 0), ('クレジットカード', 1), ('QR決済', 2), ('その他', 3)
on conflict (name) do nothing;
