create table if not exists public.credit_card_providers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0
);

alter table public.credit_card_providers enable row level security;

drop policy if exists "Allow public credit card provider access"
  on public.credit_card_providers;

create policy "Allow public credit card provider access"
  on public.credit_card_providers
  for all
  to anon
  using (true)
  with check (true);

insert into public.credit_card_providers (name, sort_order)
values
  ('楽天カード', 0),
  ('三井住友カード', 1),
  ('PayPayカード', 2),
  ('その他', 3)
on conflict (name) do nothing;

-- Authentication foundation. Set the first user's role to admin after
-- creating the account in Supabase Auth.
create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "Users can read their own role"
  on public.user_roles;

create policy "Users can read their own role"
  on public.user_roles
  for select
  to authenticated
  using (user_id = auth.uid() or public.is_admin());
