create table if not exists public.credit_card_providers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0
);

alter table public.credit_card_providers enable row level security;

drop policy if exists "Allow public credit card provider access"
  on public.credit_card_providers;

create policy "Allow public credit card provider access"
  on public.credit_card_providers
  for all
  to anon
  using (true)
  with check (true);

insert into public.credit_card_providers (name, sort_order)
values
  ('楽天カード', 0),
  ('三井住友カード', 1),
  ('PayPayカード', 2),
  ('その他', 3)
on conflict (name) do nothing;
