-- Run this migration once in the Supabase SQL Editor after the first account
-- has been created. The first Auth user receives the existing data.

begin;

create table if not exists public.user_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

alter table public.user_roles
  add column if not exists disabled boolean not null default false;

create table if not exists public.user_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.user_roles enable row level security;
alter table public.user_audit_logs enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid() and role = 'admin' and not disabled
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

do $$
declare
  owner_id uuid;
  table_name text;
begin
  select id into owner_id
  from auth.users
  order by created_at
  limit 1;

  if owner_id is null then
    raise exception 'Create the first Supabase Auth account before running this migration';
  end if;

  foreach table_name in array array[
    'kakeibo',
    'categories',
    'payment_methods',
    'qr_payment_providers',
    'credit_card_providers',
    'auto_buttons',
    'auto_schedules'
  ] loop
    execute format('alter table public.%I add column if not exists user_id uuid references auth.users(id) on delete cascade', table_name);
    execute format('update public.%I set user_id = %L where user_id is null', table_name, owner_id);
    execute format('alter table public.%I alter column user_id set not null', table_name);
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from anon', table_name);
    execute format('grant select, insert, update, delete on table public.%I to authenticated', table_name);

    execute format('drop policy if exists "User scoped access" on public.%I', table_name);
    execute format(
      'create policy "User scoped access" on public.%I for all to authenticated using (user_id = auth.uid() and not exists (select 1 from public.user_roles where user_id = auth.uid() and disabled)) with check (user_id = auth.uid() and not exists (select 1 from public.user_roles where user_id = auth.uid() and disabled))',
      table_name
    );

    execute format('create or replace function public.set_%I_user_id() returns trigger language plpgsql security invoker as $fn$ begin new.user_id := auth.uid(); return new; end; $fn$', table_name);
    execute format('drop trigger if exists set_user_id on public.%I', table_name);
    execute format('create trigger set_user_id before insert on public.%I for each row execute function public.set_%I_user_id()', table_name, table_name);
  end loop;
end $$;

insert into public.user_roles (user_id, role)
select id, 'admin'
from auth.users
order by created_at
limit 1
on conflict (user_id) do update set role = 'admin';

revoke all on table public.user_roles from anon;
grant select on table public.user_roles to authenticated;

drop policy if exists "Users can read their own role" on public.user_roles;
create policy "Users can read their own role"
  on public.user_roles
  for select
  to authenticated
  using (user_id = auth.uid() or public.is_admin());

create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication is required';
  end if;

  delete from auth.users where id = auth.uid();
end;
$$;

revoke all on function public.delete_my_account() from public;
grant execute on function public.delete_my_account() to authenticated;

create or replace function public.admin_list_users()
returns table (user_id uuid, email text, role text, disabled boolean, created_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select u.id, u.email, coalesce(r.role, 'user'), coalesce(r.disabled, false), u.created_at
  from auth.users u
  left join public.user_roles r on r.user_id = u.id
  where public.is_admin()
  order by u.created_at;
$$;

create or replace function public.admin_update_user(
  target_user_id uuid,
  new_role text,
  new_disabled boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Administrator permission is required';
  end if;
  if target_user_id = auth.uid() and (new_role <> 'admin' or new_disabled) then
    raise exception 'You cannot remove your own administrator access';
  end if;
  if new_role not in ('user', 'admin') then
    raise exception 'Invalid role';
  end if;
  insert into public.user_roles (user_id, role, disabled)
  values (target_user_id, new_role, new_disabled)
  on conflict (user_id) do update
    set role = excluded.role, disabled = excluded.disabled;
  insert into public.user_audit_logs (actor_user_id, target_user_id, action, details)
  values (auth.uid(), target_user_id, 'user_updated', jsonb_build_object('role', new_role, 'disabled', new_disabled));
end;
$$;

create or replace function public.admin_delete_user(target_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Administrator permission is required';
  end if;
  if target_user_id = auth.uid() then
    raise exception 'You cannot delete your own account here';
  end if;
  if not exists (select 1 from auth.users where id = target_user_id) then
    raise exception 'User not found';
  end if;
  insert into public.user_audit_logs (actor_user_id, target_user_id, action)
  values (auth.uid(), target_user_id, 'user_deleted');
  delete from auth.users where id = target_user_id;
end;
$$;

create or replace function public.admin_list_audit_logs()
returns table (id bigint, actor_user_id uuid, target_user_id uuid, action text, details jsonb, created_at timestamptz)
language sql
security definer
set search_path = public
as $$
  select l.id, l.actor_user_id, l.target_user_id, l.action, l.details, l.created_at
  from public.user_audit_logs l
  where public.is_admin()
  order by l.created_at desc
  limit 100;
$$;

revoke all on function public.admin_list_users() from public;
grant execute on function public.admin_list_users() to authenticated;
revoke all on function public.admin_update_user(uuid, text, boolean) from public;
grant execute on function public.admin_update_user(uuid, text, boolean) to authenticated;
revoke all on function public.admin_delete_user(uuid) from public;
grant execute on function public.admin_delete_user(uuid) to authenticated;
revoke all on function public.admin_list_audit_logs() from public;
grant execute on function public.admin_list_audit_logs() to authenticated;

commit;
